india_info = {
    "Country": "India",
    "Capital": "New Delhi",
    "Population": "1.4 billion",
    "Area_sq_km": 3287263,
    "Official_languages": ["Hindi", "English"],
    "Currency": "Indian Rupee (INR)",
    "President": "Droupadi Murmu",
    "Prime_Minister": "Narendra Modi",
    "Independence_Day": "15 August 1947",
    "National_Animal": "Bengal Tiger",
    "National_Bird": "Indian Peacock",
    "National_Flower": "Lotus",
    "National_Fruit": "Mango",
    "Famous_River": "Ganges",
    "Highest_Mountain": "Kangchenjunga",
    "Largest_City": "Mumbai",
    "Major_Religions": ["Hinduism", "Islam", "Christianity", "Sikhism"],
    "Democracy": True,
    "Famous_Festival": "Diwali",
    "Major_Exports": ["Petroleum products", "Jewelry", "Pharmaceuticals"],
    "Major_Industries": ["IT", "Textiles", "Automobile"],
    "National_Sport": "Field Hockey",
    "UN_Member_Since": 1945,
    "GDP_USD": "3.73 trillion",
    "Literacy_Rate_Percent": 77,
    "Time_Zone": "IST (UTC+5:30)",
    "Calling_Code": "+91",
    "Internet_TLD": ".in",
    "Famous_Monument": "Taj Mahal",
    "Constitution_Adopted": "26 January 1950"
}
for key in india_info:
    print(f"{key} {india_info[key]}")